name: fuel_checker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  google_maps_flutter: ^2.2.5
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  provider: ^6.1.1
  http: ^0.13.5
  fl_chart: ^0.70.2

  flutter_rating_bar: ^4.0.1
  mailer: ^6.0.1
  email_validator: ^2.1.17


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Total Energies.png
    - assets/images/zuva energy.png
    - assets/images/energy park.png
    - assets/images/Fuelcheck logo 150by1.png
    - assets/images/Facebook Icon.png
    - assets/images/apple icon logo.png
    - assets/images/Black Google Icon.png
    - assets/fonts/
    - assets/icons/
