name: fuelcheckzw
description: "A fuel price tracking application for Zimbabwe."
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Updated to enable super-parameters
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.9.1
  firebase_messaging: ^14.7.0

  # Location & Maps
  geolocator: ^10.1.1
  geocoding: ^2.1.0
  google_maps_flutter: ^2.2.3
  flutter_polyline_points: ^1.0.0
  http: ^0.13.6

  # UI & Utilities
  provider: ^6.1.1
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.70.2
  logger: ^2.5.0
  email_validator: ^3.0.0
  mailer: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: GoogleIcons
      fonts:
        - asset: assets/fonts/google_icons.ttf
