name: fuel_checker
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "^3.6.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.0
  flutter_map_directions: ^0.0.8
  fl_chart: ^0.70.2
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  email_validator: ^3.0.0
  mailer: ^6.4.1  # Downgrade to a compatible version
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.0.0
  firebase_data_connect: ^0.1.1
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo-full-color-150-x-1.png
    - lib/assets/images/map_background.png
    - lib/assets/images/Favourites.png
    - lib/assets/images/Trends.png
    - lib/assets/images/my trips.png
    - lib/assets/images/Settings.png

    - lib/assets/images/nearby.png
