name: fuel_check
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "^3.6.0" # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0 # Updated logger package
  flutter_map: ^7.0.2 # Updated flutter_map package
  geolocator: ^13.0.2 # Updated geolocator package
  latlong2: ^0.9.1 # Updated latlong2 package
  geocoding: ^3.0.0 # Updated geocoding package
  http: ^0.12.2 # Updated to a compatible version
  email_validator: ^3.0.0 # Updated email_validator package
  google_maps_flutter: ^2.0.0 # Added google_maps_flutter package
  flutter_rating_bar: ^4.0.1 # Updated flutter_rating_bar package
  fl_chart: ^0.70.2
  mailer: ^6.0.0 # Added mailer package
  provider: ^6.0.0 # Added provider package
  flutter_svg: ^1.0.0 # Added flutter_svg package
  google_fonts: ^2.1.0 # Added Google Fonts package

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - web/icons/Icon-maskable-512.png
    - lib/assets/images/Fuelcheck logo 150by1.png # Updated to correct asset path
    - lib/assets/images/Facebook Icon.png # Updated to replace space with %20
    - lib/assets/images/apple icon logo.png # Updated to replace space with %20
    - lib/assets/images/Black Google Icon.png # Updated to replace space with %20

  fonts:
    - family: GoogleIcons
      fonts:
        - asset: fonts/google_icons.ttf
