# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting performance.
# Disable this by adding the following line:
# analytics_disabled = true

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'OneSignal', '>= 3.0.0'

end
